export const books = [
    {
        id: 1,
        title: "The Lost Expedition",
        desc: "Embark on a thrilling journey through uncharted territories, facing perilous challenges and discovering ancient secrets.",
        img: "/Library/images/adventure 1.png",
        genre: 'adventure',
        price: 24.9,
    },
    {
        id: 2,
        title: "The Forbidden Artifact",
        desc: "Unravel the mysteries of a crime-ridden city as you delve deep into its underworld, following clues and uncovering dark secrets.",
        img: "/Library/images/adventure 2.png",
        genre: 'adventure',
        price: 29.9,
    },
    {
        id: 3,
        title: "The Hidden Kingdom",
        desc: "Enter a realm of magic and wonder, where mythical creatures roam and epic battles determine the fate of kingdoms.",
        img: "/Library/images/adventure 3.png",
        genre: 'adventure',
        price: 19.9,
    },
    {
        id: 4,
        title: "The Quest for Destiny",
        desc: "Embark on a perilous quest to fulfill your destiny, braving treacherous landscapes and confronting powerful adversaries.",
        img: "/Library/images/adventure 4.png",
        genre: 'adventure',
        price: 27.5,
    },
    {
        id: 5,
        title: "The Last Stand",
        desc: "Join a band of courageous heroes as they face their greatest challenge yet, battling against overwhelming odds to save their world from destruction.",
        img: "/Library/images/adventure 5.png",
        genre: 'adventure',
        price: 22.9,
    },
    {
        id: 6,
        title: "The Mysterious Case",
        desc: "Step into the shoes of a seasoned detective as you investigate a series of baffling crimes, piecing together clues and solving puzzles to uncover the truth.",
        img: "/Library/images/crime 2.png",
        genre: 'crime',
        price: 34.5,
    },
    {
        id: 7,
        title: "The Dark Alley",
        desc: "Navigate the shadowy streets of a crime-infested city, where danger lurks around every corner and secrets are buried deep within the urban jungle.",
        img: "/Library/images/crime 3.png",
        genre: 'crime',
        price: 26.9,
    },
    {
        id: 8,
        title: "The Silent Witness",
        desc: "Enter a world of deceit and betrayal, where nothing is as it seems and everyone has something to hide.",
        img: "/Library/images/crime 4.png",
        genre: 'crime',
        price: 31.2,
    },
    {
        id: 9,
        title: "The Enchanted Realm",
        desc: "Discover a magical land of wonders, where dreams come to life and fantastical creatures roam free.",
        img: "/Library/images/fantasy 1.png",
        genre: 'fantasy',
        price: 19.9,
    },
    {
        id: 10,
        title: "The Chronicles of Destiny",
        desc: "Embark on an epic quest to fulfill an ancient prophecy, battling dark forces and forging alliances in a world on the brink of chaos.",
        img: "/Library/images/fantasy 2.png",
        genre: 'fantasy',
        price: 28.7,
    },
    {
        id: 11,
        title: "The Dragon's Lair",
        desc: "Journey to a land of dragons and magic, where brave warriors seek fame and fortune in the shadow of towering mountains and ancient ruins.",
        img: "/Library/images/fantasy 3.png",
        genre: 'fantasy',
        price: 25.3,
    },
    {
        id: 12,
        title: "The Crystal Kingdom",
        desc: "Explore a realm of crystal palaces and enchanted forests, where danger and adventure await at every turn.",
        img: "/Library/images/fantasy 4.png",
        genre: 'fantasy',
        price: 30.8,
    },
    {
        id: 13,
        title: "The Ordinary Life",
        desc: "Embark on a journey of self-discovery and personal growth, as you uncover the secrets to living a fulfilling and meaningful life.",
        img: "/Library/images/normal 1.png",
        genre: 'normal',
        price: 21.5,
    },
    {
        id: 14,
        title: "The Path to Success",
        desc: "Unlock your true potential and achieve your goals, as you learn valuable lessons from the world's most successful individuals.",
        img: "/Library/images/normal 2.png",
        genre: 'normal',
        price: 23.8,
    },
    {
        id: 15,
        title: "The Journey Within",
        desc: "Embark on a transformative journey of self-discovery and personal growth, as you explore the depths of your own mind and spirit.",
        img: "/Library/images/normal 3.png",
        genre: 'normal',
        price: 26.1,
    },
    {
        id: 16,
        title: "The Road to Happiness",
        desc: "Discover the keys to lasting happiness and fulfillment, as you embark on a journey of self-discovery and personal growth.",
        img: "/Library/images/normal 4.png",
        genre: 'normal',
        price: 29.4,
    },
    {
        id: 17,
        title: "The Galactic Odyssey",
        desc: "Embark on an epic journey across the stars, exploring distant galaxies and encountering strange new worlds in a quest for knowledge and adventure.",
        img: "/Library/images/science fiction 1.png",
        genre: 'science fiction',
        price: 32.7,
    },
    {
        id: 18,
        title: "The Future Within",
        desc: "Explore the frontiers of science and technology, as you delve into the possibilities and perils of a future shaped by human ingenuity.",
        img: "/Library/images/self-development 1.png",
        genre: 'self-development',
        price: 27.8,
    },
    {
        id: 19,
        title: "The Dark Secrets",
        desc: "Uncover the dark secrets hidden beneath the surface of a seemingly idyllic small town, as you unravel a web of lies and deceit.",
        img: "/Library/images/crime 1.png",
        genre: 'crime',
        price: 24.3,
    },
    {
        id: 20,
        title: "The Midnight Heist",
        desc: "Embark on a daring heist through the dark alleys and hidden corners of the city, where danger lurks at every turn and betrayal is always a step away.",
        img: "/Library/images/crime 5.png",
        genre: 'crime',
        price: 28.6,
    },
    {
        id: 21,
        title: "The Interstellar Voyage",
        desc: "Embark on an epic journey across the cosmos, exploring distant planets and encountering strange alien civilizations in a quest for knowledge and adventure.",
        img: "/Library/images/science fiction 2.png",
        genre: 'science fiction',
        price: 31.9,
    },
    {
        id: 22,
        title: "The Cybernetic Revolution",
        desc: "Explore a future where humanity and technology merge, as you navigate a world of advanced AI, cybernetic enhancements, and virtual realities.",
        img: "/Library/images/science fiction 3.png",
        genre: 'science fiction',
        price: 29.5,
    },
    {
        id: 23,
        title: "The Galactic Empire",
        desc: "Join the ranks of an interstellar empire, as you rise through the ranks to become a legendary commander in the battle for control of the galaxy.",
        img: "/Library/images/science fiction 4.png",
        genre: 'science fiction',
        price: 33.2,
    },
    {
        id: 24,
        title: "The Time Traveler's Dilemma",
        desc: "Step into the shoes of a time traveler, navigating the complexities of temporal paradoxes and alternate realities in a quest to save the future.",
        img: "/Library/images/science fiction 5.png",
        genre: 'science fiction',
        price: 27.8,
    },
    {
        id: 25,
        title: "The Underworld Chronicles",
        desc: "Descend into the seedy underworld of organized crime, as you navigate a web of deceit and betrayal in search of justice and redemption.",
        img: "/Library/images/crime 6.png",
        genre: 'crime',
        price: 26.3,
    },
    {
        id: 26,
        title: "The Criminal Syndicate",
        desc: "Infiltrate a notorious criminal syndicate, as you rise through the ranks to become a mastermind of deception and intrigue.",
        img: "/Library/images/crime 7.png",
        genre: 'crime',
        price: 30.1,
    },
    {
        id: 27,
        title: "The Diamond Heist",
        desc: "Plan and execute the ultimate heist, as you gather a team of skilled criminals to steal a priceless diamond from under the nose of a ruthless crime lord.",
        img: "/Library/images/crime 8.png",
        genre: 'crime',
        price: 28.7,
    },
    {
        id: 28,
        title: "The Legendary Explorer",
        desc: "Embark on a daring expedition to uncharted lands, braving treacherous terrain and ancient ruins in search of fame and fortune.",
        img: "/Library/images/adventure 7.png",
        genre: 'adventure',
        price: 25.6,
    },
    {
        id: 29,
        title: "The Pirate's Treasure",
        desc: "Sail the high seas in search of hidden treasure, battling rival pirates and mythical creatures in a swashbuckling adventure.",
        img: "/Library/images/adventure 8.png",
        genre: 'adventure',
        price: 23.9,
    },
    {
        id: 30,
        title: "The Lost City of Gold",
        desc: "Discover the legendary lost city of gold, hidden deep within the Amazon rainforest, as you unravel the secrets of an ancient civilization.",
        img: "/Library/images/adventure 9.png",
        genre: 'adventure',
        price: 27.4,
    }
    
];
